### ISSUE TITLE
"Input Error: Incorrect ncuts." error message.

### ISSUE THREAD

**Issue by filipecn** [sungeui/OpenCCL#2]
Hi,

I modified the Demo.cpp file to run a simple mesh example and I keep receiving an error that is apparently related to metis. The example is as follows:

mesh:

 0      --      1
 |      \       |       \
 2      __      3       -- 4

where inside Demo.cpp I added the lines:
...
  const int NumVertex = 5;
...
  Graph.AddEdge(1, 4);
  Graph.AddEdge(3, 4);
...

I basically added another triangle to the original example.  When I run, I receive the following error:
Input Error: Incorrect ncuts.
After postprocessing of Metis, the number of clusters is less than 2 

I tried to compile metis directly and update the libmetis.a inside the "Lib" folder but with no success. I'm currently doing all this on ArchLinux with g++ version 7.3.1. 
I compiled and run following the instructions on the README.txt, no extra commands.

Thank you very much.

**Comment by sungeui** [comment]
Hi,

I also found the exactly same problem in my windows setting with VC 2013.

To figure out the problem, I got a copy of the metis library and recompiled it.
It then suddenly works!

For the simple mesh setting that you showed, I now get the following result:
------
 A sample mesh:
 0      --      1
 |         \\          |          \\
 2      __      3       __ 4
Computed vertex order:
ID of 0th position in the computed order is 4
ID of 1th position in the computed order is 1
ID of 2th position in the computed order is 3
ID of 3th position in the computed order is 0
ID of 4th position in the computed order is 2
---------------------------

I don't know why we had the problem, but maybe I got an incorrect version of the metis library??

Now I need to recompile the metis library in a linux, but I don't have a linux environment that I can readily use.

It may take some time for the linux case.

Thanks,
Sung-eui

p.s., I uploaded re-compiled metis library in both release and debug modes.

**Comment by sungeui** [comment]
While I need some more time to try out the linux case, I uploaded source codes of metis that I got.
You can try it out and compile in your linux setting.

You can now see the metis-4.0 folder in the root directory.

Let me know if you run into any issue.

Thanks,
Sung-eui

**Comment by sungeui** [comment]
Hmm, I tried lots of things in my linux environment.
I think that I found why it causes the problem; some of libraries are compiled differently in 32 bit and 64 bit.

An easy fix didn't work.
I'll look into more once I get some more time later.

Thanks,

**Comment by filipecn** [comment]
Oh I see, makes sense. I'll try to check my metis compilation over my linux.

**Comment by sungeui** [comment]
Under windows, codes are working well even with 64 bit.
Somehow, I got a very odd linking error or runtime error under 64 bit linux..

**Comment by filipecn** [comment]
No worries.

I tried on the windows as you told and everything worked very well. 

Maybe it is related to some specific compilation process under linux, if I discover something later I let you know. For now I'll stick with windows with no problem.

Thanks again!

**Comment by sungeui** [comment]
Thanks,
Sung-eui

**Comment by HeechanShin** [comment]
Now we upload correct version of metis and it works on Linux 64 bit.
Additionally, we will test on various OSs.
